CREATE SCHEMA EC2_SI1N;

USE EC2_SI1N;

CREATE TABLE IF NOT EXISTS Passageiros(
PASS_CPF INT PRIMARY KEY,
PASS_NOME VARCHAR(45) NOT NULL,
PASS_TELEFONE INT NOT NULL,
PASS_ENDEREÇO VARCHAR (20) NOT NULL
);

CREATE TABLE IF NOT EXISTS Voos(
VOO_COD INT PRIMARY KEY,
VOO_ORIGEM VARCHAR (45) NOT NULL,
VOO_DESTINO VARCHAR(45) NOT NULL,
VOO_HORÁRIO TIME (35) NOT NULL
);

CREATE TABLE IF NOT EXISTS Aeroportos(
AEROPORTO_COD INT PRIMARY KEY,
AEROPORTO_NOME VARCHAR (30) NOT NULL,
AEROPORTO_LOCAL VARCHAR (35) NOT NULL,
AEROPORTO_PAÍS VARCHAR (25) NOT NULL,
AEROPORTO_LONGITUDE INT NOT NULL,
AEROPORTO_LATITUDE INT NOT NULL,
);

CREATE TABLE IF NOT EXISTS Aeronaves(
AERONAVE_PREFIXO INT PRIMARY KEY,
AERONAVE_MODELO VARCHAR (35) NOT NULL,
AERONAVE_ANOFABR DATE NOT NULL,
AERONAVE_CAPACIDADE VARCHAR (50) NOT NULL,
AERONAVE_FABRICANTE VARCHAR (35) NOT NULL
);

CREATE TABLE IF NOT EXISTS Funcionários(
FUNC_ID INT PRIMARY KEY,
FUNC_FUNÇÃO VARCHAR (30) NOT NULL,
FUNC_NOME VARCHAR (50) NOT NULL,
FUNC_DATANASC DATE NOT NULL,
FUNC_TELEFONE INT NOT NULL
);

CREATE TABLE IF NOT EXISTS Reservas(
VOO_COD INT FOREIGN KEY,
PASS_CPF INT FOREIGN KEY
);

CREATE TABLE IF NOT EXISTS Operações_Voo
