CREATE SCHEMA EC2_SI1N;

USE EC2_SI1N;

CREATE TABLE IF NOT EXISTS PASSAGEIROS(
PASS_CPF INT PRIMARY KEY,
PASS_NOME VARCHAR(45) NOT NULL,
PASS_TELEFONE VARCHAR(15) NOT NULL,
PASS_ENDERECO VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS VOOS(
VOO_COD INT PRIMARY KEY,
VOO_ORIGEM VARCHAR(45) NOT NULL,
VOO_DESTINO VARCHAR(45) NOT NULL,
VOO_HORARIO TIME NOT NULL
);

CREATE TABLE IF NOT EXISTS AEROPORTOS(
AEROPORTO_COD INT PRIMARY KEY,
AEROPORTO_NOME VARCHAR(30) NOT NULL,
AEROPORTO_LOCAL VARCHAR(35) NOT NULL,
AEROPORTO_PAIS VARCHAR(25) NOT NULL,
AEROPORTO_LONGITUDE DECIMAL(9,6) NOT NULL,
AEROPORTO_LATITUDE DECIMAL(9,6) NOT NULL
);

CREATE TABLE IF NOT EXISTS AERONAVES(
AERONAVE_PREFIXO INT PRIMARY KEY,
AERONAVE_MODELO VARCHAR(35) NOT NULL,
AERONAVE_ANOFABR DATE NOT NULL,
AERONAVE_CAPACIDADE INT NOT NULL,
AERONAVE_FABRICANTE VARCHAR(35) NOT NULL
);

CREATE TABLE IF NOT EXISTS FUNCIONARIOS(
FUNC_ID INT PRIMARY KEY,
FUNC_FUNCAO VARCHAR(30) NOT NULL,
FUNC_NOME VARCHAR(50) NOT NULL,
FUNC_DATANASC DATE NOT NULL,
FUNC_TELEFONE VARCHAR(15) NOT NULL
);

CREATE TABLE IF NOT EXISTS RESERVAS(
VOO_COD INT,
PASS_CPF INT,
);

CREATE TABLE IF NOT EXISTS VOOS_PASSAGEIROS(
VOO_COD INT,
PASS_CPF INT,
PRIMARY KEY(VOO_COD, PASS_CPF),
CONSTRAINT FK_VOOS_PASSAGEIROS_VOOS FOREIGN KEY(VOO_COD) REFERENCES VOOS(VOO_COD),
CONSTRAINT FK_VOOS_PASSAGEIROS_PASSAGEIROS FOREIGN KEY(PASS_CPF) REFERENCES PASSAGEIROS(PASS_CPF)
);

ALTER TABLE PASSAGEIROS ADD PASS_EMAIL VARCHAR(50);
ALTER TABLE PASSAGEIROS DROP PASS_ENDERECO;
ALTER TABLE PASSAGEIROS MODIFY PASS_NOME VARCHAR(100) NOT NULL;
ALTER TABLE PASSAGEIROS CHANGE PASS_NOME PASS_NOME_COMPLETO VARCHAR(100) NOT NULL;

ALTER TABLE VOOS ADD VOO_DATA DATE NOT NULL;
ALTER TABLE VOOS DROP VOO_HORARIO;
ALTER TABLE VOOS MODIFY VOO_ORIGEM VARCHAR(100) NOT NULL;
ALTER TABLE VOOS CHANGE VOO_DESTINO VOO_DESTINO_NOVO VARCHAR(100) NOT NULL;

ALTER TABLE AEROPORTOS ADD AEROPORTO_CONTINENTE VARCHAR(30);
ALTER TABLE AEROPORTOS DROP AEROPORTO_LOCAL;
ALTER TABLE AEROPORTOS MODIFY AEROPORTO_NOME VARCHAR(50) NOT NULL;
ALTER TABLE AEROPORTOS CHANGE AEROPORTO_PAIS AEROPORTO_PAIS_NOVO VARCHAR(30) NOT NULL;

ALTER TABLE AERONAVES ADD AERONAVE_ANOS_SERVICO INT;
ALTER TABLE AERONAVES DROP AERONAVE_CAPACIDADE;
ALTER TABLE AERONAVES MODIFY AERONAVE_MODELO VARCHAR(50) NOT NULL;
ALTER TABLE AERONAVES CHANGE AERONAVE_FABRICANTE AERONAVE_FABRICANTE_NOVO VARCHAR(50) NOT NULL;

ALTER TABLE FUNCIONARIOS ADD FUNC_EMAIL VARCHAR(50);
ALTER TABLE FUNCIONARIOS DROP FUNC_TELEFONE;
ALTER TABLE FUNCIONARIOS MODIFY FUNC_NOME VARCHAR(100) NOT NULL;
ALTER TABLE FUNCIONARIOS CHANGE FUNC_FUNCAO FUNC_CARGO VARCHAR(30) NOT NULL;

ALTER TABLE RESERVAS ADD RESERVA_DATA DATE NOT NULL;
ALTER TABLE RESERVAS DROP PASS_CPF;
ALTER TABLE RESERVAS MODIFY VOO_COD INT NOT NULL;
ALTER TABLE RESERVAS CHANGE VOO_COD RESERVA_VOO_COD INT NOT NULL;

ALTER TABLE VOOS_PASSAGEIROS ADD NUM_ASSENTO VARCHAR(10);
ALTER TABLE VOOS_PASSAGEIROS DROP PASS_CPF;
ALTER TABLE VOOS_PASSAGEIROS MODIFY VOO_COD INT NOT NULL;
ALTER TABLE VOOS_PASSAGEIROS CHANGE VOO_COD VOOS_COD INT NOT NULL;
ALTER TABLE VOOS_PASSAGEIROS ADD DATA_RESERVA DATE NOT NULL;

DROP TABLE IF EXISTS RESERVAS;
