CREATE SCHEMA EC2_SI1N;

USE EC2_SI1N;

CREATE TABLE IF NOT EXISTS PASSAGEIROS(
PASS_CPF INT PRIMARY KEY,
PASS_NOME VARCHAR(45) NOT NULL,
PASS_TELEFONE INT NOT NULL,
PASS_ENDERECO VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS VOOS(
VOO_COD INT PRIMARY KEY,
VOO_ORIGEM VARCHAR(45) NOT NULL,
VOO_DESTINO VARCHAR(45) NOT NULL,
VOO_HORARIO TIME(35) NOT NULL
);

CREATE TABLE IF NOT EXISTS AEROPORTOS(
AEROPORTO_COD INT PRIMARY KEY,
AEROPORTO_NOME VARCHAR(30) NOT NULL,
AEROPORTO_LOCAL VARCHAR(35) NOT NULL,
AEROPORTO_PAIS VARCHAR(25) NOT NULL,
AEROPORTO_LONGITUDE INT NOT NULL,
AEROPORTO_LATITUDE INT NOT NULL
);

CREATE TABLE IF NOT EXISTS AERONAVES(
AERONAVE_PREFIXO INT PRIMARY KEY,
AERONAVE_MODELO VARCHAR(35) NOT NULL,
AERONAVE_ANOFABR DATE NOT NULL,
AERONAVE_CAPACIDADE VARCHAR(50) NOT NULL,
AERONAVE_FABRICANTE VARCHAR(35) NOT NULL
);

CREATE TABLE IF NOT EXISTS FUNCIONARIOS(
FUNC_ID INT PRIMARY KEY,
FUNC_FUNCAO VARCHAR(30) NOT NULL,
FUNC_NOME VARCHAR(50) NOT NULL,
FUNC_DATANASC DATE NOT NULL,
FUNC_TELEFONE INT NOT NULL
);

CREATE TABLE IF NOT EXISTS RESERVAS(
VOO_COD INT,
PASS_CPF INT,
PRIMARY KEY(VOO_COD, PASS_CPF),
CONSTRAINT FK_VOOS FOREIGN KEY(VOO_COD) REFERENCES VOOS(VOO_COD),
CONSTRAINT FK_PASSAGEIROS FOREIGN KEY(PASS_CPF) REFERENCES PASSAGEIROS(PASS_CPF)
);

CREATE TABLE IF NOT EXISTS FUNCIONARIOS_VOOS(
FUNC_ID INT,
VOO_COD INT,
PRIMARY KEY(FUNC_ID, VOO_COD),
CONSTRAINT FK_FUNCIONARIOS FOREIGN KEY(FUNC_ID) REFERENCES FUNCIONARIOS(FUNC_ID),
CONSTRAINT FK_VOOS FOREIGN KEY(VOO_COD) REFERENCES VOOS(VOO_COD)
);
