CREATE SCHEMA EC3_SI1N;

USE EC3SI1N;

ALTER TABLE CLIENTES 
ADD EMAIL VARCHAR(50);

ALTER TABLE CLIENTES 
DROP COLUMN NOME_CLIENTE;

ALTER TABLE CLIENTES 
MODIFY CNPJ_CLIENTE VARCHAR(16);

ALTER TABLE CLIENTES 
CHANGE CNPJ_CLIENTE CNPJ_CLIENTE_FISICO VARCHAR(16);


CREATE TABLE IF NOT EXISTS CLIENTES(
COD_CLIENTE INT PRIMARY KEY,
CNPJ_CLIENTE INT NOT NULL,
NOME_CLIENTE VARCHAR(45) NOT NULL,
RAZAO_SOCIAL_CLIENTE INT NOT NULL,
RAMO_ATIVIDADE VARCHAR(15) NOT NULL,
DATA_CADASTRAMENTO DATE NOT NULL,
PESSOA_CONTATO VARCHAR(45) NOT NULL
);

CREATE TABLE IF NOT EXISTS EMPREGADOS(
EMPREGADO_MATRICULA INT PRIMARY KEY,
EMPREGADO_NOME VARCHAR(45) NOT NULL,
EMPREGADO_CARGO VARCHAR(15) NOT NULL,
EMPREGADO_SALARIO INT NOT NULL,
EMPREGADO_ADMISSÃO DATE NOT NULL,
EMPREGADO_QUALIFICACOES TEXT NOT NULL,
EMPREGADO_ENDEREÇO INT NOT NULL
);

CREATE TABLE IF NOT EXISTS EMPRESAS(
EMPRESAS_CNPJ INT PRIMARY KEY,
EMPRESAS_RAZAO_SOCIAL INT NOT NULL,
EMPRESAS_PESSOA_CONTATO VARCHAR(45) NOT NULL
);

CREATE TABLE IF NOT EXISTS FORNECEDORES(
FORN_CNPJ INT PRIMARY KEY,
FORN_RAZAO_SOCIAL INT NOT NULL,
FORN_PESSOA_CONTATO VARCHAR(45) NOT NULL
);

CREATE TABLE IF NOT EXISTS TIPO_DE_ENDERECO(
TIP_END_COD INT PRIMARY KEY,
TIP_END_NOME VARCHAR(45) NOT NULL
);

CREATE TABLE IF NOT EXISTS ENDEREÇOS (
END_NUM INT PRIMARY KEY,
END_LOGRADOURO VARCHAR(150),
END_COMPLEMENTO VARCHAR(50),
END_CEP VARCHAR(10),
END_BAIRRO VARCHAR(50),
END_CIDADE VARCHAR(50),
END_ESTADO VARCHAR(2)
);


CREATE TABLE IF NOT EXISTS ENCOMENDAS(
ENC_NUM INT PRIMARY KEY,
ENC_DATA_INCLUSÃO DATE NOT NULL,
ENC_VALOR_TOTAL INT NOT NULL,
ENC_VALOR_DESCONTO INT NOT NULL,
ENC_VALOR_LÍQUIDO INT NOT NULL,
ENC_ID_FORMA_PAGAMENTO INT NOT NULL,
ENC_QUANT_PARCELA INT NOT NULL
);

CREATE TABLE IF NOT EXISTS PRODUTOS(
PROD_COD INT PRIMARY KEY,
PROD_NOME VARCHAR(45) NOT NULL,
PROD_COR VARCHAR(30),
PROD_DIM VARCHAR(50),
PROD_PESO DECIMAL(10, 2),
PROD_PRECO DECIMAL(10, 2),
PROD_TEMP_FABRICACAO INT,
PROD_DESENHO TEXT,
HORAS_MAO_OBRA DECIMAL(5, 2)
);

CREATE TABLE IF NOT EXISTS TIPOS_DE_COMPONENTE(
TIP_COMP_COD INT PRIMARY KEY,
TIP_COMP_NOME VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS COMPONENTES(
COMP_COD INT PRIMARY KEY AUTO_INCREMENT,
COMP_NOME VARCHAR(100) NOT NULL,
COMP_QUANTIDADE_ESTOQUE INT NOT NULL,
COMP_PRECO_UNITARIO DECIMAL(10, 2) NOT NULL,
COMP_UNIDADE VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS MAQUINAS(
MAQ_TEMPO_VIDA INT NOT NULL,
MAQ_DATA_COMPRA DATE NOT NULL,
MAQ_DATA_FIM_GARANTIA DATE
);

CREATE TABLE IF NOT EXISTS RE(Recursos_Específicos)(
RE_QUANTIDADE_NECESSARIA INT NOT NULL,
RE_UNIDADE VARCHAR(50) NOT NULL,
RE_TEMPO_USO INT,
RE_HORAS_MAO_OBRA DECIMAL(5, 2)
);

CREATE TABLE IF NOT EXISTS RM(Registro_de_Manutenção)(
RM_DATA DATE NOT NULL,
RM_DESCRICAO VARCHAR(200) NOT NULL,
);

CREATE TABLE IF NOT EXISTS RS(Registro_de_Suprimentos)(
RS_QUANTIDADE INT NOT NULL,
RS_DATA_NECESSIDADE DATE NOT NULL,
);

CREATE TABLE IF NOT EXISTS TELEFONE(
TEL_NUM INT PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS PESSOA CONTATO(
CONTATO_ID INT PRIMARY KEY
);
